# Generated by Django 3.2 on 2022-12-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_owner_flats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ФИО владельца'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер владельца'),
            preserve_default=False,
        ),
    ]
